(function(g){var window=this;'use strict';var rmC=function(L){L.publish("autonavvisibility")},B15=function(L,W){L.xp("onAutonavCoundownStarted",W)},AmQ=function(L){var W,f,I;
return L==null?void 0:(W=L.playerOverlays)==null?void 0:(f=W.playerOverlayRenderer)==null?void 0:(I=f.autoplay)==null?void 0:I.playerOverlayAutoplayRenderer},bv=function(L){var W=L.B(),f=W.T;
g.G.call(this,{Y:"a",j:"ytp-autonav-suggestion-card",L:{href:"{{url}}",target:f?W.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},C:[{Y:"div",d6:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],L:{style:"{{background}}"},C:[{Y:"div",L:{"aria-label":"{{timestamp}}"},d6:["ytp-autonav-timestamp"],NV:"{{duration}}"},{Y:"div",d6:["ytp-autonav-live-stamp"],NV:"Live"},{Y:"div",
d6:["ytp-autonav-upcoming-stamp"],NV:"Upcoming"},{Y:"div",j:"ytp-autonav-list-overlay",C:[{Y:"div",j:"ytp-autonav-mix-text",NV:"Mix"},{Y:"div",j:"ytp-autonav-mix-icon"}]}]},{Y:"div",d6:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],NV:"{{title}}"},{Y:"div",d6:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],NV:"{{author}}"},{Y:"div",d6:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],NV:"{{views_and_publish_time}}"}]});this.S=L;this.suggestion=
null;this.W=f;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},h1=function(L,W){W=W===void 0?!1:W;
g.G.call(this,{Y:"div",j:"ytp-autonav-endscreen-countdown-overlay"});var f=this;this.J=W;this.cancelCommand=this.G=void 0;this.N=0;this.container=new g.G({Y:"div",j:"ytp-autonav-endscreen-countdown-container"});g.C(this,this.container);this.container.OH(this.element);W=L.B();var I=W.T;this.S=L;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.D(L,"videodatachange",this.onVideoDataChange);this.W=new g.G({Y:"div",j:"ytp-autonav-endscreen-upnext-container",L:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},C:[{Y:"div",j:"ytp-autonav-endscreen-upnext-header"},{Y:"div",j:"ytp-autonav-endscreen-upnext-alternative-header",NV:"{{autoplayAlternativeHeader}}"},{Y:"a",j:"ytp-autonav-endscreen-link-container",L:{href:"{{url}}",target:I?W.X:""},C:[{Y:"div",j:"ytp-autonav-endscreen-upnext-thumbnail",L:{style:"{{background}}"},C:[{Y:"div",L:{"aria-label":"{{timestamp}}"},d6:["ytp-autonav-timestamp"],
NV:"{{duration}}"},{Y:"div",d6:["ytp-autonav-live-stamp"],NV:"Live"},{Y:"div",d6:["ytp-autonav-upcoming-stamp"],NV:"Upcoming"}]},{Y:"div",j:"ytp-autonav-endscreen-video-info",C:[{Y:"div",j:"ytp-autonav-endscreen-premium-badge"},{Y:"div",j:"ytp-autonav-endscreen-upnext-title",NV:"{{title}}"},{Y:"div",j:"ytp-autonav-endscreen-upnext-author",NV:"{{author}}"},{Y:"div",j:"ytp-autonav-view-and-date",NV:"{{views_and_publish_time}}"},{Y:"div",j:"ytp-autonav-author-and-view",NV:"{{author_and_views}}"}]}]}]});
g.C(this,this.W);this.W.OH(this.container.element);I||this.D(this.W.T1("ytp-autonav-endscreen-link-container"),"click",this.t8);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.W.T1("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.G({Y:"div",j:"ytp-autonav-overlay"});g.C(this,this.overlay);this.overlay.OH(this.container.element);this.K=new g.G({Y:"div",j:"ytp-autonav-endscreen-button-container"});g.C(this,this.K);this.K.OH(this.container.element);
this.cancelButton=new g.G({Y:"button",d6:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",W.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],L:{"aria-label":"Cancel autoplay"},NV:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.OH(this.K.element);this.cancelButton.listen("click",this.OG,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.G({Y:"a",d6:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
W.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],L:{href:"{{url}}",role:"button","aria-label":"Play next video"},NV:"Play Now"});g.C(this,this.playButton);this.playButton.OH(this.K.element);this.playButton.listen("click",this.t8,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(W=this.S.getVideoData())&&SaC(this,W);this.T=new g.sn(function(){Z5n(f)},500);
g.C(this,this.T);this.jZ();this.D(L,"autonavvisibility",this.jZ);this.S.Z("web_autonav_color_transition")&&(this.D(L,"autonavchange",this.yb),this.D(L,"onAutonavCoundownStarted",this.ygH))},Ek=function(L){var W=L.S.J7(!0,L.S.isFullscreen());
g.e2(L.container.element,"ytp-autonav-endscreen-small-mode",L.eG(W));g.e2(L.container.element,"ytp-autonav-endscreen-is-premium",!!L.suggestion&&!!L.suggestion.VGP);g.e2(L.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!L.S.GD());g.e2(L.S.getRootNode(),"countdown-running",L.jQ());g.e2(L.container.element,"ytp-player-content",L.S.GD());g.Ga(L.overlay.element,{width:W.width+"px"});if(!L.jQ()){L.S.GD()?DFc(L,Math.round(wvO(L)/1E3)):DFc(L);W=!!L.suggestion&&!!L.suggestion.wf;var f=L.S.GD()||
!W;g.e2(L.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!f&&W);g.e2(L.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",f&&!W);L.K.DE(L.S.GD());g.e2(L.element,"ytp-enable-w2w-color-transitions",zHG(L))}},Z5n=function(L){var W=wvO(L),f=Math,I=f.min;
var U=L.N?Date.now()-L.N:0;f=I.call(f,U,W);DFc(L,Math.ceil((W-f)/1E3));W-f<=500&&L.jQ()?L.select(!0):L.jQ()&&L.T.start()},wvO=function(L){if(L.S.isFullscreen()){var W;
L=(W=L.S.getVideoData())==null?void 0:W.vZ;return L===-1||L===void 0?8E3:L}return L.S.p7()>=0?L.S.p7():g.$M(L.S.B().experiments,"autoplay_time")||1E4},SaC=function(L,W){W=W.getWatchNextResponse();
var f,I;W=(f=AmQ(W))==null?void 0:(I=f.nextButton)==null?void 0:I.buttonRenderer;L.G=W==null?void 0:W.navigationEndpoint;f=W==null?void 0:W.trackingParams;L.playButton&&f&&L.S.setTrackingParams(L.playButton.element,f)},zHG=function(L){var W;
return!((W=L.S.getVideoData())==null||!W.watchToWatchTransitionRenderer)},DFc=function(L,W){W=W===void 0?-1:W;
L=L.W.T1("ytp-autonav-endscreen-upnext-header");g.ZE(L);if(W>=0){W=String(W);var f="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],I="Up next in $SECONDS".indexOf(f);if(I>=0){L.appendChild(g.Ay("Up next in $SECONDS".slice(0,I)));var U=g.Bq("span");g.LZ(U,"ytp-autonav-endscreen-upnext-header-countdown-number");g.My(U,W);L.appendChild(U);L.appendChild(g.Ay("Up next in $SECONDS".slice(I+f.length)));return}}g.My(L,"Up next")},ds=function(L,W){g.G.call(this,{Y:"div",
d6:["html5-endscreen","ytp-player-content",W||"base-endscreen"]});this.created=!1;this.player=L},vF=function(L){g.G.call(this,{Y:"div",
d6:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},C:[{Y:"div",j:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{Y:"span",j:"ytp-upnext-top",C:[{Y:"span",j:"ytp-upnext-header",NV:"Up Next"},{Y:"span",j:"ytp-upnext-title",NV:"{{title}}"},{Y:"span",j:"ytp-upnext-author",NV:"{{author}}"}]},{Y:"a",j:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},C:[{Y:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
C:[{Y:"circle",j:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Y:"circle",j:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Y:"path",j:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Y:"span",j:"ytp-upnext-bottom",C:[{Y:"span",j:"ytp-upnext-cancel"},{Y:"span",j:"ytp-upnext-paused",
NV:"Autoplay is paused"}]}]});this.api=L;this.cancelButton=null;this.G=this.T1("ytp-svg-autoplay-ring");this.N=this.notification=this.W=this.suggestion=null;this.T=new g.sn(this.Io,5E3,this);this.K=0;var W=this.T1("ytp-upnext-cancel");this.cancelButton=new g.G({Y:"button",d6:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},NV:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.listen("click",this.Mu,this);this.cancelButton.OH(W);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.C(this,this.T);this.api.createClientVe(this.element,this,18788);W=this.T1("ytp-upnext-autoplay-icon");this.D(W,"click",this.iY);this.api.createClientVe(W,this,115130);this.Vw();this.D(L,"autonavvisibility",this.Vw);this.D(L,"mdxnowautoplaying",this.KXd);this.D(L,"mdxautoplaycanceled",this.m$w);g.e2(this.element,"ytp-upnext-mobile",this.api.B().K)},MkC=function(L,W){if(W)return W;
if(L.api.isFullscreen()){var f;L=(f=L.api.getVideoData())==null?void 0:f.vZ;return L===-1||L===void 0?8E3:L}return L.api.p7()>=0?L.api.p7():g.$M(L.api.B().experiments,"autoplay_time")||1E4},nGc=function(L,W){W=MkC(L,W);
var f=Math,I=f.min;var U=(0,g.V4)()-L.K;f=I.call(f,U,W);W=W===0?1:Math.min(f/W,1);L.G.setAttribute("stroke-dashoffset",""+-211*(W+1));W>=1&&L.jQ()&&L.api.getPresentingPlayerType()!==3?L.select(!0):L.jQ()&&L.W.start()},rs=function(L){ds.call(this,L,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.G({Y:"div",j:"ytp-suggestion-panel",C:[{Y:"div",d6:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],NV:"More videos"}]});this.V=new g.G({Y:"div",j:"ytp-suggestions-container"});this.videos=[];this.N=null;this.G=this.J=!1;this.K=new h1(this.player);g.C(this,this.K);this.K.OH(this.element);L.getVideoData().Ej?this.W=this.K:(this.W=new vF(L),g.Ln(this.player,this.W.element,4),g.C(this,this.W));this.overlay=new g.G({Y:"div",
j:"ytp-autonav-overlay-cancelled-state"});g.C(this,this.overlay);this.overlay.OH(this.element);this.T=new g.XF(this);g.C(this,this.T);g.C(this,this.table);this.table.OH(this.element);this.table.show();g.C(this,this.V);this.V.OH(this.table.element);this.hide()},BF=function(L){var W=L.GD();
W!==L.G&&(L.G=W,rmC(L.player),L.G?(L.K!==L.W&&L.K.hide(),L.table.hide()):(L.K!==L.W&&L.K.show(),L.table.show()))},XvC=function(L){ds.call(this,L,"videowall-endscreen");
var W=this;this.S=L;this.stills=[];this.N=this.videoData=null;this.T=this.J=!1;this.V=null;g.$C(this.element,"modern-videowall-endscreen");this.K=new g.XF(this);g.C(this,this.K);this.G=new g.sn(function(){g.$C(W.element,"ytp-show-tiles")},0);
g.C(this,this.G);this.table=new g.U5({Y:"div",j:"ytp-modern-endscreen-content"});g.C(this,this.table);this.table.OH(this.element);L.getVideoData().Ej?this.W=new h1(L,!0):this.W=new vF(L);g.C(this,this.W);g.Ln(this.player,this.W.element,4);L.createClientVe(this.element,this,158789);this.hide()},A1=function(L){return g.Wp(L.player)&&L.WK()&&!L.N},Sr=function(L){var W=L.GD();
W!==L.J&&(L.J=W,rmC(L.player))},Vki=function(L){ds.call(this,L,"subscribecard-endscreen");
this.W=new g.G({Y:"div",j:"ytp-subscribe-card",C:[{Y:"img",j:"ytp-author-image",L:{src:"{{profilePicture}}"}},{Y:"div",j:"ytp-subscribe-card-right",C:[{Y:"div",j:"ytp-author-name",NV:"{{author}}"},{Y:"div",j:"html5-subscribe-button-container"}]}]});g.C(this,this.W);this.W.OH(this.element);var W=L.getVideoData();this.subscribeButton=new g.eI("Subscribe",null,"Unsubscribe",null,!0,!1,W.WQ,W.subscribed,"trailer-endscreen",null,L,!1);g.C(this,this.subscribeButton);this.subscribeButton.OH(this.W.T1("html5-subscribe-button-container"));
this.D(L,"videodatachange",this.fl);this.fl();this.hide()},Zm=function(L){var W=L.B(),f=g.wS||g.Oc?{style:"will-change: opacity"}:void 0,I=W.T,U=["ytp-videowall-still"];
W.K&&U.push("ytp-videowall-show-text");g.G.call(this,{Y:"a",d6:U,L:{href:"{{url}}",target:I?W.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},C:[{Y:"div",j:"ytp-videowall-still-image",L:{style:"{{background}}"}},{Y:"span",j:"ytp-videowall-still-info",L:{"aria-hidden":"true"},C:[{Y:"span",j:"ytp-videowall-still-info-bg",C:[{Y:"span",j:"ytp-videowall-still-info-content",L:f,C:[{Y:"span",j:"ytp-videowall-still-info-title",NV:"{{title}}"},
{Y:"span",j:"ytp-videowall-still-info-author",NV:"{{author_and_views}}"},{Y:"span",j:"ytp-videowall-still-info-live",NV:"Live"},{Y:"span",j:"ytp-videowall-still-info-duration",NV:"{{duration}}"}]}]}]},{Y:"span",d6:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},C:[{Y:"span",j:"ytp-videowall-still-listlabel-icon"},"Playlist",{Y:"span",j:"ytp-videowall-still-listlabel-length",C:[" (",{Y:"span",NV:"{{playlist_length}}"},")"]}]},{Y:"span",d6:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},C:[{Y:"span",j:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Y:"span",j:"ytp-videowall-still-listlabel-length",NV:" (50+)"}]}]});this.suggestion=null;this.K=I;this.api=L;this.W=new g.XF(this);g.C(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.D(L,"videodatachange",this.onVideoDataChange);L.createServerVe(this.element,this);this.onVideoDataChange()},Dm=function(L){ds.call(this,L,"videowall-endscreen");
var W=this;this.S=L;this.N=0;this.stills=[];this.T=this.videoData=null;this.G=this.V=!1;this.X=null;this.K=new g.XF(this);g.C(this,this.K);this.J=new g.sn(function(){g.$C(W.element,"ytp-show-tiles")},0);
g.C(this,this.J);var f=new g.G({Y:"button",d6:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},C:[g.B2()]});g.C(this,f);f.OH(this.element);f.listen("click",this.p6,this);this.table=new g.U5({Y:"div",j:"ytp-endscreen-content"});g.C(this,this.table);this.table.OH(this.element);f=new g.G({Y:"button",d6:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"Next"},C:[g.Ae()]});g.C(this,f);f.OH(this.element);f.listen("click",this.Zu,this);L.getVideoData().Ej?this.W=new h1(L,!0):this.W=
new vF(L);g.C(this,this.W);g.Ln(this.player,this.W.element,4);L.createClientVe(this.element,this,158789);this.hide()},ws=function(L){return g.Wp(L.player)&&L.WK()&&!L.T},zo=function(L){var W=L.GD();
W!==L.V&&(L.V=W,rmC(L.player))},mFt=function(L,W){g.G.call(this,{Y:"button",
d6:["ytp-watch-on-youtube-button","ytp-button"],NV:"{{content}}"});this.S=L;this.buttonType=this.buttonType=W;this.bJ();this.buttonType===2&&g.$C(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.bJ);this.DE(!0)},Mt=function(L){ds.call(this,L,"watch-again-on-youtube-endscreen");
this.watchButton=new mFt(L,1);g.C(this,this.watchButton);this.watchButton.OH(this.element);g.UoX(L)&&(this.W=new g.Lz(L),g.C(this,this.W),this.K=new g.G({Y:"div",d6:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],L:{tabIndex:"-1"},C:[this.W]}),g.C(this,this.K),this.W.OH(this.K.element),this.K.OH(this.element));L.createClientVe(this.element,this,156914);this.hide()},ymX=function(L){g.ux.call(this,L);
var W=this;this.endScreen=null;this.W=this.K=this.N=!1;this.listeners=new g.XF(this);g.C(this,this.listeners);var f=L.B();L.isEmbedsShortsMode()?this.endScreen=new Mt(L):u_Q(L)?(this.N=!0,KlG(this),this.W?this.endScreen=new rs(L):f.Z("delhi_modern_endscreen")?this.endScreen=new XvC(L):this.endScreen=new Dm(L)):f.N2?this.endScreen=new Vki(L):this.endScreen=new ds(L);g.C(this,this.endScreen);g.Ln(L,this.endScreen.element,4);T1A(this);this.listeners.D(L,"videodatachange",this.onVideoDataChange,this);
this.listeners.D(L,g.iW("endscreen"),function(I){W.onCueRangeEnter(I)});
this.listeners.D(L,g.xM("endscreen"),function(I){W.onCueRangeExit(I)})},KlG=function(L){var W=L.player.getVideoData();
if(!W||L.W===W.lj&&L.K===W.Ej)return!1;L.W=W.lj;L.K=W.Ej;return!0},u_Q=function(L){L=L.B();
return L.AQ&&!L.N2&&!L.disableOrganicUi},T1A=function(L){L.player.V2("endscreen");
var W=L.player.getVideoData();W=new g.sW(Math.max((W.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var f=new g.sW(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});L.player.AD([W,f])};
g.sY.prototype.p7=g.Uy(6,function(){return this.app.p7()});
g.w7.prototype.p7=g.Uy(5,function(){return this.getVideoData().kZ});
g.Ra.prototype.IC=g.Uy(4,function(L){this.jx().IC(L)});
g.Oe.prototype.IC=g.Uy(3,function(L){this.AY!==L&&(this.AY=L,this.k8())});
g.w(bv,g.G);bv.prototype.select=function(){this.S.lK(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QV||void 0)&&this.S.logClick(this.element)};
bv.prototype.onClick=function(L){g.Kn(L,this.S,this.W,this.suggestion.sessionData||void 0)&&this.select()};
bv.prototype.onKeyPress=function(L){switch(L.keyCode){case 13:case 32:L.defaultPrevented||(this.select(),L.preventDefault())}};g.w(h1,g.G);g.D=h1.prototype;g.D.j0=function(L){this.suggestion!==L&&(this.suggestion=L,g.v9(this.W,L),this.playButton.updateValue("url",this.suggestion.Iz()),Ek(this))};
g.D.jQ=function(){return this.N>0};
g.D.X6=function(){this.jQ()||(this.N=Date.now(),Z5n(this),B15(this.S,wvO(this)),g.e2(this.S.getRootNode(),"countdown-running",this.jQ()))};
g.D.v_=function(){this.Tb();Z5n(this);var L=this.W.T1("ytp-autonav-endscreen-upnext-header");L&&g.My(L,"Up next")};
g.D.Tb=function(){this.jQ()&&(this.T.stop(),this.N=0)};
g.D.select=function(L){this.S.nextVideo(!1,L===void 0?!1:L);this.Tb()};
g.D.t8=function(L){g.Kn(L,this.S)&&(L.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):L.currentTarget===this.W.T1("ytp-autonav-endscreen-link-container")&&(L=this.W.T1("ytp-autonav-endscreen-link-container"),this.S.logVisibility(L,!0),this.S.logClick(L)),this.G?(this.S.xp("innertubeCommand",this.G),this.Tb()):this.select())};
g.D.OG=function(){this.S.logClick(this.cancelButton.element);g.ik(this.S,!0);this.cancelCommand&&this.S.xp("innertubeCommand",this.cancelCommand)};
g.D.onVideoDataChange=function(L,W){SaC(this,W);L=W.getWatchNextResponse();var f,I;L=(f=AmQ(L))==null?void 0:(I=f.cancelButton)==null?void 0:I.buttonRenderer;this.cancelCommand=L==null?void 0:L.command};
g.D.ygH=function(L){if(zHG(this)){var W=this.S.getVideoData().watchToWatchTransitionRenderer,f=W==null?void 0:W.fromColorPaletteDark;W=W==null?void 0:W.toColorPaletteDark;if(f&&W){var I=this.element;I.style.setProperty("--w2w-start-background-color",g.J8(f.surgeColor));I.style.setProperty("--w2w-start-primary-text-color",g.J8(f.primaryTitleColor));I.style.setProperty("--w2w-start-secondary-text-color",g.J8(f.secondaryTitleColor));I.style.setProperty("--w2w-end-background-color",g.J8(W.surgeColor));
I.style.setProperty("--w2w-end-primary-text-color",g.J8(W.primaryTitleColor));I.style.setProperty("--w2w-end-secondary-text-color",g.J8(W.secondaryTitleColor));I.style.setProperty("--w2w-animation-duration",L+"ms")}g.e2(this.element,"ytp-w2w-animate",!0)}};
g.D.yb=function(L){this.S.Z("web_autonav_color_transition")&&L!==2&&g.e2(this.element,"ytp-w2w-animate",!1)};
g.D.jZ=function(){var L=this.S.GD();this.J&&this.Pn!==L&&this.DE(L);Ek(this);this.S.logVisibility(this.container.element,L);this.S.logVisibility(this.cancelButton.element,L);this.S.logVisibility(this.W.T1("ytp-autonav-endscreen-link-container"),L);this.S.logVisibility(this.playButton.element,L)};
g.D.eG=function(L){return L.width<400||L.height<459};g.w(ds,g.G);g.D=ds.prototype;g.D.create=function(){this.created=!0};
g.D.destroy=function(){this.created=!1};
g.D.WK=function(){return!1};
g.D.GD=function(){return!1};
g.D.wG=function(){return!1};g.w(vF,g.G);g.D=vF.prototype;g.D.Io=function(){this.notification&&(this.T.stop(),this.vT(this.N),this.N=null,this.notification.close(),this.notification=null)};
g.D.j0=function(L){this.suggestion=L;g.v9(this,L,"hqdefault.jpg")};
g.D.Vw=function(){this.DE(this.api.GD());this.api.logVisibility(this.element,this.api.GD());this.api.logVisibility(this.T1("ytp-upnext-autoplay-icon"),this.api.GD());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.GD())};
g.D.RHe=function(){window.focus();this.Io()};
g.D.X6=function(L){var W=this;this.jQ()||(g.WU("a11y-announce","Up Next "+this.suggestion.title),this.K=(0,g.V4)(),this.W=new g.sn(function(){nGc(W,L)},25),nGc(this,L),B15(this.api,MkC(this,L)));
g.IA(this.element,"ytp-upnext-autoplay-paused")};
g.D.hide=function(){g.G.prototype.hide.call(this)};
g.D.jQ=function(){return!!this.W};
g.D.v_=function(){this.Tb();this.K=(0,g.V4)();nGc(this);g.$C(this.element,"ytp-upnext-autoplay-paused")};
g.D.Tb=function(){this.jQ()&&(this.W.dispose(),this.W=null)};
g.D.select=function(L){L=L===void 0?!1:L;if(this.api.B().Z("autonav_notifications")&&L&&window.Notification&&typeof document.hasFocus==="function"){var W=Notification.permission;W==="default"?Notification.requestPermission():W!=="granted"||document.hasFocus()||(this.Io(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.EX()}),this.N=this.D(this.notification,"click",this.RHe),this.T.start())}this.Tb();this.api.nextVideo(!1,L)};
g.D.iY=function(L){!g.za(this.cancelButton.element,L.target)&&g.Kn(L,this.api)&&(this.api.GD()&&this.api.logClick(this.T1("ytp-upnext-autoplay-icon")),this.select())};
g.D.Mu=function(){this.api.GD()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.ik(this.api,!0)};
g.D.KXd=function(L){this.api.getPresentingPlayerType();this.show();this.X6(L)};
g.D.m$w=function(){this.api.getPresentingPlayerType();this.Tb();this.hide()};
g.D.w6=function(){this.Tb();this.Io();g.G.prototype.w6.call(this)};g.w(rs,ds);g.D=rs.prototype;g.D.create=function(){ds.prototype.create.call(this);this.T.D(this.player,"appresize",this.aF);this.T.D(this.player,"onVideoAreaChange",this.aF);this.T.D(this.player,"videodatachange",this.onVideoDataChange);this.T.D(this.player,"autonavchange",this.b$);this.T.D(this.player,"onAutonavCancelled",this.cW);this.onVideoDataChange()};
g.D.show=function(){ds.prototype.show.call(this);(this.J||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.ik(this.player,!1);g.Wp(this.player)&&this.WK()&&!this.N?(BF(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.X6():this.videoData.autonavState===3&&this.W.v_()):(g.ik(this.player,!0),BF(this));this.aF()};
g.D.hide=function(){ds.prototype.hide.call(this);this.W.v_();BF(this)};
g.D.aF=function(){var L=this.player.J7(!0,this.player.isFullscreen());BF(this);Ek(this.K);g.e2(this.element,"ytp-autonav-cancelled-small-mode",this.eG(L));g.e2(this.element,"ytp-autonav-cancelled-tiny-mode",this.Zf(L));g.e2(this.element,"ytp-autonav-cancelled-mini-mode",L.width<=400||L.height<=360);this.overlay&&g.Ga(this.overlay.element,{width:L.width+"px"});if(!this.G)for(L=0;L<this.videos.length;L++)g.e2(this.videos[L].element,"ytp-suggestion-card-with-margin",L%2===1)};
g.D.onVideoDataChange=function(){var L=this.player.getVideoData();if(this.videoData!==L&&L){this.videoData=L;if((L=this.videoData.suggestions)&&L.length||this.player.Z("web_player_autonav_empty_suggestions_fix")){var W=g.mk(this.videoData);W&&(this.W.j0(W),this.W!==this.K&&this.K.j0(W))}if(L&&L.length)for(W=0;W<gGt.length;++W){var f=gGt[W];if(L&&L[f]){this.videos[W]=new bv(this.player);var I=this.videos[W];f=L[f];I.suggestion!==f&&(I.suggestion=f,g.v9(I,f));g.C(this,this.videos[W]);this.videos[W].OH(this.V.element)}}this.aF()}};
g.D.b$=function(L){L===1?(this.J=!1,this.N=this.videoData.clientPlaybackNonce,this.W.Tb(),this.Pn&&this.aF()):(this.J=!0,this.GD()&&(L===2?this.W.X6():L===3&&this.W.v_()))};
g.D.cW=function(L){L?this.b$(1):(this.N=null,this.J=!1)};
g.D.WK=function(){return this.videoData.autonavState!==1};
g.D.eG=function(L){return(L.width<910||L.height<459)&&!this.Zf(L)&&!(L.width<=400||L.height<=360)};
g.D.Zf=function(L){return L.width<800&&!(L.width<=400||L.height<=360)};
g.D.GD=function(){return this.Pn&&g.Wp(this.player)&&this.WK()&&!this.N};
var gGt=[1,3,2,4];g.w(XvC,ds);g.D=XvC.prototype;g.D.create=function(){ds.prototype.create.call(this);var L=this.player.getVideoData();L&&(this.videoData=L);this.gJ();this.K.D(this.player,"appresize",this.gJ);this.K.D(this.player,"onVideoAreaChange",this.gJ);this.K.D(this.player,"videodatachange",this.onVideoDataChange);this.K.D(this.player,"autonavchange",this.U_);this.K.D(this.player,"onAutonavCancelled",this.gq);L=this.videoData.autonavState;L!==this.V&&this.U_(L);this.K.D(this.element,"transitionend",this.Sl)};
g.D.destroy=function(){g.T4(this.K);g.IW(this.stills);this.stills=[];ds.prototype.destroy.call(this);g.IA(this.element,"ytp-show-tiles");this.G.stop();this.V=this.videoData.autonavState};
g.D.WK=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var L=this.Pn;ds.prototype.show.call(this);g.IA(this.element,"ytp-show-tiles");this.player.B().K?g.i$(this.G):this.G.start();(this.T||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.ik(this.player,!1);A1(this)?(Sr(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.X6():this.videoData.autonavState===3&&this.W.v_()):(g.ik(this.player,!0),Sr(this));L!==this.Pn&&this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var L=this.Pn;ds.prototype.hide.call(this);this.W.v_();Sr(this);L!==this.Pn&&this.player.logVisibility(this.element,!1)};
g.D.Sl=function(L){L.target===this.element&&this.gJ()};
g.D.gJ=function(){var L,W,f,I;var U=((L=this.videoData)==null?0:(W=L.suggestions)==null?0:W.length)?(f=this.videoData)==null?void 0:f.suggestions:[(I=this.videoData)==null?void 0:g.mk(I)];if(U.length){W=this.S.J7(!0,this.S.isFullscreen());L=Math.floor((W.width-64+16)/(g.Cb(W.width*.27,250,450)+16));W=Math.min(3,Math.floor((W.height-64)/((W.width-64-(L-1)*16)/L*.5625+70)));g.UF(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.$C(this.element,"ytp-modern-endscreen-limit-rows-"+W);g.e2(this.element,"ytp-modern-endscreen-single-item",L===1);g.e2(this.element,"ytp-modern-endscreen-row-0",W===0);L=this.table.element;L.ariaLive="polite";this.W.j0(g.mk(this.videoData));this.W instanceof h1&&Ek(this.W);g.e2(this.element,"ytp-endscreen-takeover",A1(this));Sr(this);W=0;L.ariaBusy="true";f=U.length;for(I=0;I<f;I++){var e=I%f,b=this.stills[I];b||(b=new g.rx(this.player),this.stills[I]=b,L.appendChild(b.element));g.lRR(b,U[e]);W++}this.stills.length=
W}};
g.D.onVideoDataChange=function(){var L=this.player.getVideoData(1);this.videoData!==L&&(L!=null&&g.mk(L)?(this.videoData=L,this.gJ()):this.player.mw("missg",{vid:(L==null?void 0:L.videoId)||"",cpn:(L==null?void 0:L.clientPlaybackNonce)||""}))};
g.D.wG=function(){return this.W.jQ()};
g.D.U_=function(L){L===1?(this.T=!1,this.N=this.videoData.clientPlaybackNonce,this.W.Tb(),this.Pn&&this.gJ()):(this.T=!0,this.Pn&&A1(this)&&(L===2?this.W.X6():L===3&&this.W.v_()))};
g.D.gq=function(L){if(L){for(L=0;L<this.stills.length;L++)this.S.logVisibility(this.stills[L].element,!0);this.U_(1)}else this.N=null,this.T=!1;this.gJ()};
g.D.GD=function(){return this.Pn&&A1(this)};g.w(Vki,ds);Vki.prototype.fl=function(){var L=this.player.getVideoData();this.W.update({profilePicture:L.profilePicture,author:L.author});this.subscribeButton.channelId=L.WQ;var W=this.subscribeButton;L.subscribed?W.W():W.K()};g.w(Zm,g.G);Zm.prototype.select=function(){this.api.lK(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QV||void 0)&&this.api.logClick(this.element)};
Zm.prototype.onClick=function(L){if(g.Wz(this.api.B())&&this.api.Z("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var W=this.suggestion.Iz(),f={};g.Hw(this.api,f);W=g.Dr(W,f);g.T8(W,this.api,L)}else g.Kn(L,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
Zm.prototype.onKeyPress=function(L){switch(L.keyCode){case 13:case 32:L.defaultPrevented||(this.select(),L.preventDefault())}};
Zm.prototype.onVideoDataChange=function(){var L=this.api.getVideoData(),W=this.api.B();this.K=L.ly?!1:W.T};g.w(Dm,ds);g.D=Dm.prototype;g.D.create=function(){ds.prototype.create.call(this);var L=this.player.getVideoData();L&&(this.videoData=L);this.TC();this.K.D(this.player,"appresize",this.TC);this.K.D(this.player,"onVideoAreaChange",this.TC);this.K.D(this.player,"videodatachange",this.onVideoDataChange);this.K.D(this.player,"autonavchange",this.X3);this.K.D(this.player,"onAutonavCancelled",this.n6);L=this.videoData.autonavState;L!==this.X&&this.X3(L);this.K.D(this.element,"transitionend",this.Fn)};
g.D.destroy=function(){g.T4(this.K);g.IW(this.stills);this.stills=[];ds.prototype.destroy.call(this);g.IA(this.element,"ytp-show-tiles");this.J.stop();this.X=this.videoData.autonavState};
g.D.WK=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var L=this.Pn;ds.prototype.show.call(this);g.IA(this.element,"ytp-show-tiles");this.player.B().K?g.i$(this.J):this.J.start();(this.G||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.ik(this.player,!1);ws(this)?(zo(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.X6():this.videoData.autonavState===3&&this.W.v_()):(g.ik(this.player,!0),zo(this));L!==this.Pn&&this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var L=this.Pn;ds.prototype.hide.call(this);this.W.v_();zo(this);L!==this.Pn&&this.player.logVisibility(this.element,!1)};
g.D.Fn=function(L){L.target===this.element&&this.TC()};
g.D.TC=function(){var L,W,f,I;var U=((L=this.videoData)==null?0:(W=L.suggestions)==null?0:W.length)?(f=this.videoData)==null?void 0:f.suggestions:[(I=this.videoData)==null?void 0:g.mk(I)];if(U.length){g.$C(this.element,"ytp-endscreen-paginate");var e=this.S.J7(!0,this.S.isFullscreen());if(L=g.YK(this.S))L=L.yP()?48:32,e.width-=L*2;var b=e.width/e.height;I=96/54;W=L=2;var E=Math.max(e.width/96,2),d=Math.max(e.height/54,2);f=U.length;var v=f*4;for(v-=4;v>0&&(L<E||W<d);){var r=L/2,B=W/2,A=L<=E-2&&v>=
B*4,S=W<=d-2&&v>=r*4;if((r+1)/B*I/b>b/(r/(B+1)*I)&&S)v-=r*4,W+=2;else if(A)v-=B*4,L+=2;else if(S)v-=r*4,W+=2;else break}I=!1;v>=12&&f*4-v<=6&&(W>=4||L>=4)&&(I=!0);v=L*96;E=W*54;b=v/E<b?e.height/E:e.width/v;b=Math.min(b,2);v=Math.floor(Math.min(e.width,v*b));E=Math.floor(Math.min(e.height,E*b));e=this.table.element;e.ariaLive="polite";g.Ls(e,v,E);g.Ga(e,{marginLeft:v/-2+"px",marginTop:E/-2+"px"});this.W.j0(g.mk(this.videoData));this.W instanceof h1&&Ek(this.W);g.e2(this.element,"ytp-endscreen-takeover",
ws(this));zo(this);v+=4;E+=4;b=0;e.ariaBusy="true";for(d=0;d<L;d++)for(r=0;r<W;r++)if(B=b,S=0,I&&d>=L-2&&r>=W-2?S=1:r%2===0&&d%2===0&&(r<2&&d<2?r===0&&d===0&&(S=2):S=2),B=g.pb(B+this.N,f),S!==0){A=this.stills[b];A||(A=new Zm(this.player),this.stills[b]=A,e.appendChild(A.element));var Z=Math.floor(E*r/W),M=Math.floor(v*d/L),m=Math.floor(E*(r+S)/W)-Z-4,T=Math.floor(v*(d+S)/L)-M-4;g.kk(A.element,M,Z);g.Ls(A.element,T,m);g.Ga(A.element,"transitionDelay",(r+d)/20+"s");g.e2(A.element,"ytp-videowall-still-mini",
S===1);g.e2(A.element,"ytp-videowall-still-large",S>2);S=Math.max(T,m);g.e2(A.element,"ytp-videowall-still-round-large",S>=256);g.e2(A.element,"ytp-videowall-still-round-medium",S>96&&S<256);g.e2(A.element,"ytp-videowall-still-round-small",S<=96);B=U[B];A.suggestion!==B&&(A.suggestion=B,S=A.api.B(),Z=g.Wj(A.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.v9(A,B,Z),g.Wz(S)&&!A.api.Z("web_player_log_click_before_generating_ve_conversion_params")&&(S=B.Iz(),Z={},g.QT(A.api,"addEmbedsConversionTrackingParams",
[Z]),S=g.Dr(S,Z),A.updateValue("url",S)),(B=(B=B.sessionData)&&B.itct)&&A.api.setTrackingParams(A.element,B));b++}e.ariaBusy="false";g.e2(this.element,"ytp-endscreen-paginate",b<f);for(U=this.stills.length-1;U>=b;U--)L=this.stills[U],g.wy(L.element),g.fi(L);this.stills.length=b}};
g.D.onVideoDataChange=function(){var L=this.player.getVideoData(1);this.videoData!==L&&(L!=null&&g.mk(L)?(this.N=0,this.videoData=L,this.TC()):this.player.mw("missg",{vid:(L==null?void 0:L.videoId)||"",cpn:(L==null?void 0:L.clientPlaybackNonce)||""}))};
g.D.Zu=function(){this.N+=this.stills.length;this.TC()};
g.D.p6=function(){this.N-=this.stills.length;this.TC()};
g.D.wG=function(){return this.W.jQ()};
g.D.X3=function(L){L===1?(this.G=!1,this.T=this.videoData.clientPlaybackNonce,this.W.Tb(),this.Pn&&this.TC()):(this.G=!0,this.Pn&&ws(this)&&(L===2?this.W.X6():L===3&&this.W.v_()))};
g.D.n6=function(L){if(L){for(L=0;L<this.stills.length;L++)this.S.logVisibility(this.stills[L].element,!0);this.X3(1)}else this.T=null,this.G=!1;this.TC()};
g.D.GD=function(){return this.Pn&&ws(this)};g.w(mFt,g.G);g.D=mFt.prototype;g.D.bJ=function(){switch(this.buttonType){case 1:var L="Watch again on YouTube";var W=156915;break;case 2:L="Continue watching on YouTube";W=156942;break;default:L="Continue watching on YouTube",W=156942}this.update({content:L});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,W)};
g.D.onClick=function(L){this.S.Z("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.T8(this.getVideoUrl(),this.S,L);this.S.Z("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)};
g.D.getVideoUrl=function(){var L=!0;switch(this.buttonType){case 1:L=!0;break;case 2:L=!1}L=this.S.getVideoUrl(L,!1,!1,!0);var W=this.S.B();if(g.Wz(W)){var f={};g.Wz(W)&&g.QT(this.S,"addEmbedsConversionTrackingParams",[f]);L=g.Dr(L,f)}return L};
g.D.logVisibility=function(){this.S.logVisibility(this.element,this.Pn&&this.U)};
g.D.show=function(){g.G.prototype.show.call(this);this.logVisibility()};
g.D.hide=function(){g.G.prototype.hide.call(this);this.logVisibility()};
g.D.N$=function(L){g.G.prototype.N$.call(this,L);this.logVisibility()};g.w(Mt,ds);Mt.prototype.hasSuggestions=function(){var L;return(L=this.W)==null?void 0:L.hasSuggestions()};
Mt.prototype.show=function(){if(this.player.getPlayerState()!==3){ds.prototype.show.call(this);var L=this.K;if(L){var W=this.W.hasSuggestions();g.e2(this.element,"ytp-shorts-branded-ui",W);W?L.show():L.hide()}var f;(f=g.YK(this.player))==null||f.IC(!0);this.player.logVisibility(this.element,!0);this.watchButton.N$(!0)}};
Mt.prototype.hide=function(){ds.prototype.hide.call(this);var L;(L=g.YK(this.player))==null||L.IC(!1);this.player.logVisibility(this.element,!1);this.watchButton.N$(!1)};g.w(ymX,g.ux);g.D=ymX.prototype;g.D.UN=function(){var L=this.player.getVideoData(),W=L.mutedAutoplay&&(L.limitedPlaybackDurationInSeconds>0||L.endSeconds>0||L.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!W)return!0;var f;var I=!!((L==null?0:g.mk(L))||(L==null?0:(f=L.suggestions)==null?0:f.length));I=!u_Q(this.player)||I;L=L.Xo;f=this.player.Hr();return I&&!L&&!f&&!W};
g.D.GD=function(){return this.endScreen.GD()};
g.D.KwH=function(){return this.GD()?this.endScreen.wG():!1};
g.D.w6=function(){this.player.V2("endscreen");g.ux.prototype.w6.call(this)};
g.D.load=function(){var L=this.player.getVideoData();var W=L.transitionEndpointAtEndOfStream;if(W&&W.videoId){var f=this.player.g1().Xz.get("heartbeat"),I=g.mk(L);!I||W.videoId!==I.videoId||L.oA?(this.player.lK(W.videoId,void 0,void 0,!0,!0,W),f&&f.fF("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),L=!0):L=!1}else L=!1;L||(g.ux.prototype.load.call(this),this.endScreen.show())};
g.D.unload=function(){g.ux.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.D.onCueRangeEnter=function(L){this.UN()&&(this.endScreen.created||this.endScreen.create(),L.getId()==="load"&&this.load())};
g.D.onCueRangeExit=function(L){L.getId()==="load"&&this.loaded&&this.unload()};
g.D.onVideoDataChange=function(){T1A(this);this.N&&KlG(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.W?this.endScreen=new rs(this.player):this.endScreen=new Dm(this.player),g.C(this,this.endScreen),g.Ln(this.player,this.endScreen.element,4))};g.mD("endscreen",ymX);})(_yt_player);
